---
tags:
  - Rust
  - panic
  - Result
参考: https://course.rs/basic/result-error/intro.html
---
Rust中错误通常分两类：  
- 可恢复错误 ——`Result<T, E>`  
- 不可恢复错误 ——`panic!`   
## panic!  
- 作用时提供两种终止方式  
	- 默认的**栈展开**：开启`debug`标志，以及使用`RUST_BACKTRACE=1 cargo run`命令  
	- **直接终止**：修改`Cargo.toml`  
```
[profile.release]
panic = 'abort'
```

- 主动使用场合：**失败就panic!**  
	- 通过`unwrap/expect`方法，错误不处理，直接`panic`
		- `unwrap()`
		- `expect("输出些提示文本")`  

## Result<T, E>  
首先，这是一个枚举类型：  
```
enum Result<T, E> {
    Ok(T),
    Err(E),
}
```

一个简单的用法例子：  
```
use std::fs::File;

fn main() {
    let f = File::open("hello.txt");

    let f = match f {
        Ok(file) => file,
        Err(error) => {
            panic!("Problem opening the file: {:?}", error)
        },
    };
}
```

### `?`操作符  
这是一个宏，用法与match很像  

用于以下形式：  
- `let v = xxx()?;`  
- `xxx()?.yyy()?;`  

它需要一个变量来承载正确值，或者**直接返回错误**